### ISSUE TITLE
Incorrect scaling factor for lux value

### ISSUE THREAD

**Issue by drtimf** [CoreElectronics/CE-PiicoDev-VEML6030-MicroPython-Module#2]
Hi,
Based on the design specification from Vishay:
   https://www.vishay.com/docs/84367/designingveml6030.pdf
And on page 5 of this document, a gain of 1 and an integration time of 100ms requires a scaling factor of 0.0576.
![image](https://user-images.githubusercontent.com/47528202/129600315-aefad9e5-15d7-4ccb-8df9-5baf0c81a821.png)

The implementation here has "self.res = 0.0288 # lx/bit" which needs to be changed to 0.0576 instead.

Tim

**Comment by CoreProduction** [comment]
Thanks for your contribution! This is now fixed in commit [4052aff](https://github.com/CoreElectronics/CE-PiicoDev-VEML6030-MicroPython-Module/commit/4052affd6bba0b68f936f90d722c3a3d8343b62e)
